version: "3"

services:
  backend:
    container_name: fastapi_app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  curl-runner:
    container_name: curl-runner
    image: curlimages/curl:7.85.0
    depends_on:
      - backend
    volumes:
      - ./test_api.sh:/test_api.sh
    networks:
      - app-network
    entrypoint: ["sh", "/test_api.sh"]


networks:
  app-network:
    driver: bridge
